/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ItensRouteImport } from './routes/itens'
import { Route as LicencaRouteImport } from './routes/licenca'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PrecificacaoRouteImport } from './routes/precificacao'
import { Route as PrimeirosPassosRouteImport } from './routes/primeiros-passos'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as ApiPublicMercadopagoRouteImport } from './routes/api/public/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensRoute = ItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencaRoute = LicencaRouteImport.update({
  id: '/licenca',
  path: '/licenca',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecificacaoRoute = PrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeirosPassosRoute = PrimeirosPassosRouteImport.update({
  id: '/primeiros-passos',
  path: '/primeiros-passos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoRoute = ApiPublicMercadopagoRouteImport.update({
  id: '/api/public/mercadopago',
  path: '/api/public/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administracao': typeof AdministracaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/health': typeof HealthRoute
  '/historico': typeof HistoricoRoute
  '/itens': typeof ItensRoute
  '/licenca': typeof LicencaRoute
  '/pagamentos': typeof PagamentosRoute
  '/painel': typeof PainelRoute
  '/precificacao': typeof PrecificacaoRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulador': typeof SimuladorRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administracao': typeof AdministracaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/health': typeof HealthRoute
  '/historico': typeof HistoricoRoute
  '/itens': typeof ItensRoute
  '/licenca': typeof LicencaRoute
  '/pagamentos': typeof PagamentosRoute
  '/painel': typeof PainelRoute
  '/precificacao': typeof PrecificacaoRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulador': typeof SimuladorRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/administracao': typeof AdministracaoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/despesas': typeof DespesasRoute
  '/entrar': typeof EntrarRoute
  '/equipe': typeof EquipeRoute
  '/health': typeof HealthRoute
  '/historico': typeof HistoricoRoute
  '/itens': typeof ItensRoute
  '/licenca': typeof LicencaRoute
  '/pagamentos': typeof PagamentosRoute
  '/painel': typeof PainelRoute
  '/precificacao': typeof PrecificacaoRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulador': typeof SimuladorRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/administracao'
    | '/configuracoes'
    | '/despesas'
    | '/entrar'
    | '/equipe'
    | '/health'
    | '/historico'
    | '/itens'
    | '/licenca'
    | '/pagamentos'
    | '/painel'
    | '/precificacao'
    | '/primeiros-passos'
    | '/redefinir-senha'
    | '/relatorios'
    | '/simulador'
    | '/api/public/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/administracao'
    | '/configuracoes'
    | '/despesas'
    | '/entrar'
    | '/equipe'
    | '/health'
    | '/historico'
    | '/itens'
    | '/licenca'
    | '/pagamentos'
    | '/painel'
    | '/precificacao'
    | '/primeiros-passos'
    | '/redefinir-senha'
    | '/relatorios'
    | '/simulador'
    | '/api/public/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/administracao'
    | '/configuracoes'
    | '/despesas'
    | '/entrar'
    | '/equipe'
    | '/health'
    | '/historico'
    | '/itens'
    | '/licenca'
    | '/pagamentos'
    | '/painel'
    | '/precificacao'
    | '/primeiros-passos'
    | '/redefinir-senha'
    | '/relatorios'
    | '/simulador'
    | '/api/public/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdministracaoRoute: typeof AdministracaoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DespesasRoute: typeof DespesasRoute
  EntrarRoute: typeof EntrarRoute
  EquipeRoute: typeof EquipeRoute
  HealthRoute: typeof HealthRoute
  HistoricoRoute: typeof HistoricoRoute
  ItensRoute: typeof ItensRoute
  LicencaRoute: typeof LicencaRoute
  PagamentosRoute: typeof PagamentosRoute
  PainelRoute: typeof PainelRoute
  PrecificacaoRoute: typeof PrecificacaoRoute
  PrimeirosPassosRoute: typeof PrimeirosPassosRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SimuladorRoute: typeof SimuladorRoute
  ApiPublicMercadopagoRoute: typeof ApiPublicMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens': {
      id: '/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof ItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenca': {
      id: '/licenca'
      path: '/licenca'
      fullPath: '/licenca'
      preLoaderRoute: typeof LicencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precificacao': {
      id: '/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof PrecificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiros-passos': {
      id: '/primeiros-passos'
      path: '/primeiros-passos'
      fullPath: '/primeiros-passos'
      preLoaderRoute: typeof PrimeirosPassosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago': {
      id: '/api/public/mercadopago'
      path: '/api/public/mercadopago'
      fullPath: '/api/public/mercadopago'
      preLoaderRoute: typeof ApiPublicMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdministracaoRoute: AdministracaoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DespesasRoute: DespesasRoute,
  EntrarRoute: EntrarRoute,
  EquipeRoute: EquipeRoute,
  HealthRoute: HealthRoute,
  HistoricoRoute: HistoricoRoute,
  ItensRoute: ItensRoute,
  LicencaRoute: LicencaRoute,
  PagamentosRoute: PagamentosRoute,
  PainelRoute: PainelRoute,
  PrecificacaoRoute: PrecificacaoRoute,
  PrimeirosPassosRoute: PrimeirosPassosRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  SimuladorRoute: SimuladorRoute,
  ApiPublicMercadopagoRoute: ApiPublicMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
